
version: "3.7"
services:
  app:
    build:
      args:
        user: peter
        uid: 1004
      context: ./
      dockerfile: Dockerfile
    image: evaluation_db
    container_name: evaluation_db
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
       - app-network
  db:
    image: mysql:8.0
    container_name: evaluation_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/evaluationdb.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge